/**
 * Post-Interview Feedback Report
 * Generated by AI after the session ends. Displays structured evaluation
 * with scores, strengths, weaknesses, and actionable next steps.
 */

import { FC } from 'react';
import { motion } from 'motion/react';
import {
  Trophy,
  TrendingUp,
  TrendingDown,
  Target,
  ArrowLeft,
  Star,
  Download,
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export interface FeedbackData {
  overallScore: number; // 1-10
  duration: string; // e.g. "12 min"
  mode: 'coding' | 'system-design' | 'behavioral';
  problemTitle: string;
  categories: {
    name: string;
    score: number; // 1-10
    comment: string;
  }[];
  strengths: string[];
  improvements: string[];
  nextSteps: string[];
  transcript?: string;
}

interface FeedbackReportProps {
  feedback: FeedbackData;
  onClose: () => void;
}

const ScoreRing: FC<{ score: number; size?: number }> = ({
  score,
  size = 120,
}) => {
  const radius = (size - 12) / 2;
  const circumference = 2 * Math.PI * radius;
  const progress = (score / 10) * circumference;
  const color =
    score >= 8
      ? '#22c55e'
      : score >= 6
        ? '#3b82f6'
        : score >= 4
          ? '#eab308'
          : '#ef4444';

  return (
    <div className="relative" style={{ width: size, height: size }}>
      <svg width={size} height={size} className="-rotate-90">
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke="rgba(255,255,255,0.05)"
          strokeWidth={8}
        />
        <motion.circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke={color}
          strokeWidth={8}
          strokeLinecap="round"
          strokeDasharray={circumference}
          initial={{ strokeDashoffset: circumference }}
          animate={{ strokeDashoffset: circumference - progress }}
          transition={{ duration: 1.5, ease: 'easeOut' }}
        />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <motion.span
          className="text-3xl font-black"
          style={{ color }}
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.5 }}
        >
          {score}
        </motion.span>
        <span className="text-[10px] text-gray-500 uppercase tracking-wider">
          / 10
        </span>
      </div>
    </div>
  );
};

const MiniBar: FC<{ score: number }> = ({ score }) => {
  const color =
    score >= 8
      ? 'bg-green-500'
      : score >= 6
        ? 'bg-blue-500'
        : score >= 4
          ? 'bg-yellow-500'
          : 'bg-red-500';

  return (
    <div className="flex items-center gap-2 flex-1">
      <div className="flex-1 h-2 rounded-full bg-white/5 overflow-hidden">
        <motion.div
          className={`h-full rounded-full ${color}`}
          initial={{ width: 0 }}
          animate={{ width: `${score * 10}%` }}
          transition={{ duration: 1, ease: 'easeOut', delay: 0.3 }}
        />
      </div>
      <span className="text-xs font-bold text-gray-400 w-6 text-right">
        {score}
      </span>
    </div>
  );
};

export const FeedbackReport: FC<FeedbackReportProps> = ({
  feedback,
  onClose,
}) => {
  const navigate = useNavigate();

  const modeLabel =
    feedback.mode === 'coding'
      ? '💻 Coding Interview'
      : feedback.mode === 'system-design'
        ? '🏗️ System Design'
        : '🗣️ Behavioral Interview';

  const handleExport = () => {
    const text = [
      `MockInterview.ai — Feedback Report`,
      `${'='.repeat(40)}`,
      `Mode: ${modeLabel}`,
      `Problem: ${feedback.problemTitle}`,
      `Duration: ${feedback.duration}`,
      `Overall Score: ${feedback.overallScore}/10`,
      '',
      `Category Scores:`,
      ...feedback.categories.map(
        (c) => `  ${c.name}: ${c.score}/10 — ${c.comment}`
      ),
      '',
      `Strengths:`,
      ...feedback.strengths.map((s) => `  ✅ ${s}`),
      '',
      `Areas for Improvement:`,
      ...feedback.improvements.map((s) => `  ⚠️ ${s}`),
      '',
      `Next Steps:`,
      ...feedback.nextSteps.map((s, i) => `  ${i + 1}. ${s}`),
    ].join('\n');

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `feedback-${feedback.problemTitle.toLowerCase().replace(/\s+/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-6"
    >
      <motion.div
        initial={{ opacity: 0, y: 40, scale: 0.95 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        transition={{ duration: 0.4, ease: 'easeOut' }}
        className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-3xl border border-white/10 bg-[#0d1117] shadow-2xl"
      >
        {/* Header */}
        <div className="sticky top-0 z-10 flex items-center justify-between px-6 py-4 border-b border-white/10 bg-[#0d1117]/95 backdrop-blur-md rounded-t-3xl">
          <div>
            <h2 className="text-lg font-black text-white flex items-center gap-2">
              <Trophy size={20} className="text-amber-400" />
              Interview Report
            </h2>
            <p className="text-xs text-gray-500 mt-0.5">
              {modeLabel} · {feedback.problemTitle} · {feedback.duration}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleExport}
              className="flex items-center gap-1.5 rounded-lg bg-white/5 px-3 py-1.5 text-xs text-gray-400 hover:text-white hover:bg-white/10 transition-colors cursor-pointer"
            >
              <Download size={14} />
              Export
            </button>
          </div>
        </div>

        <div className="p-6 space-y-8">
          {/* Overall Score */}
          <div className="flex flex-col items-center text-center">
            <ScoreRing score={feedback.overallScore} />
            <p className="mt-3 text-sm text-gray-400">Overall Performance</p>
          </div>

          {/* Category Breakdown */}
          <div>
            <h3 className="text-sm font-bold text-white mb-4 flex items-center gap-2">
              <Star size={14} className="text-blue-400" />
              Score Breakdown
            </h3>
            <div className="space-y-3">
              {feedback.categories.map((cat) => (
                <div key={cat.name}>
                  <div className="flex items-center gap-3 mb-1">
                    <span className="text-xs font-semibold text-gray-300 w-36 shrink-0">
                      {cat.name}
                    </span>
                    <MiniBar score={cat.score} />
                  </div>
                  <p className="text-[11px] text-gray-500 ml-36 pl-2">
                    {cat.comment}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Strengths */}
          <div>
            <h3 className="text-sm font-bold text-white mb-3 flex items-center gap-2">
              <TrendingUp size={14} className="text-green-400" />
              Strengths
            </h3>
            <ul className="space-y-2">
              {feedback.strengths.map((s, i) => (
                <motion.li
                  key={i}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.5 + i * 0.1 }}
                  className="flex items-start gap-2 text-sm text-gray-300"
                >
                  <span className="text-green-500 mt-0.5 shrink-0">✅</span>
                  {s}
                </motion.li>
              ))}
            </ul>
          </div>

          {/* Improvements */}
          <div>
            <h3 className="text-sm font-bold text-white mb-3 flex items-center gap-2">
              <TrendingDown size={14} className="text-yellow-400" />
              Areas for Improvement
            </h3>
            <ul className="space-y-2">
              {feedback.improvements.map((s, i) => (
                <motion.li
                  key={i}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.8 + i * 0.1 }}
                  className="flex items-start gap-2 text-sm text-gray-300"
                >
                  <span className="text-yellow-500 mt-0.5 shrink-0">⚠️</span>
                  {s}
                </motion.li>
              ))}
            </ul>
          </div>

          {/* Next Steps */}
          <div>
            <h3 className="text-sm font-bold text-white mb-3 flex items-center gap-2">
              <Target size={14} className="text-purple-400" />
              Recommended Next Steps
            </h3>
            <ol className="space-y-2">
              {feedback.nextSteps.map((s, i) => (
                <motion.li
                  key={i}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 1 + i * 0.1 }}
                  className="flex items-start gap-2 text-sm text-gray-300"
                >
                  <span className="text-purple-400 mt-0.5 shrink-0 text-xs font-bold">
                    {i + 1}.
                  </span>
                  {s}
                </motion.li>
              ))}
            </ol>
          </div>
        </div>

        {/* Footer */}
        <div className="sticky bottom-0 flex items-center justify-between px-6 py-4 border-t border-white/10 bg-[#0d1117]/95 backdrop-blur-md rounded-b-3xl">
          <button
            onClick={() => navigate('/')}
            className="flex items-center gap-1.5 text-sm text-gray-400 hover:text-white transition-colors cursor-pointer"
          >
            <ArrowLeft size={16} />
            Back to Home
          </button>
          <button
            onClick={onClose}
            className="rounded-xl bg-blue-600 px-5 py-2 text-sm font-semibold text-white hover:bg-blue-500 transition-colors cursor-pointer"
          >
            Try Another Problem
          </button>
        </div>
      </motion.div>
    </motion.div>
  );
};
