# Cloud Build Production Deployment
# Final pipeline for deploying to the production environment.
steps:
   
  - name: "gcr.io/cloud-builders/gcloud-slim"
    id: trigger-deployment
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "mockinterview-agent"
      - "--image"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME"
      - "--region"
      - "$_REGION"
      - "--project"
      - $_PROD_PROJECT_ID

substitutions:
  _PROD_PROJECT_ID: YOUR_PROD_PROJECT_ID
  _REGION: us-central1

logsBucket: gs://${PROJECT_ID}-mockinterview-agent-logs/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
